// save game code
// save file is stored locally. only 1 for now.

ini_open(working_directory + "rpgsave.ini")

//PLayer 1 stats
ini_write_string("Player1","name",global.name[1])
ini_write_string("Player1","class",global.class[1])
ini_write_string("Player1","status",global.status[1])
ini_write_real("Player1","hp",global.hp[1])
ini_write_real("Player1","mp",global.mp[1])
ini_write_real("Player1","xp",global.xp[1])
ini_write_real("Player1","xp_up",global.xp_up[1])
ini_write_real("Player1","level",global.level[1])
ini_write_real("Player1","maxhp",global.maxhp[1])
ini_write_real("Player1","maxmp",global.maxmp[1])
ini_write_real("Player1","atk",global.atk[1])
ini_write_real("Player1","def",global.def[1])
ini_write_real("Player1","pow",global.pow[1])
ini_write_real("Player1","res",global.res[1])
ini_write_real("Player1","spd",global.spd[1])
ini_write_real("Player1","attack1",global.attack[1,0]) 
ini_write_real("Player1","attack2",global.attack[1,1]) 
ini_write_real("Player1","attack3",global.attack[1,2]) 
ini_write_real("Player1","attack4",global.attack[1,3]) 
ini_write_real("Player1","weapon",global.weapon[1])
ini_write_real("Player1","armor",global.armor[1])
ini_write_real("Player1","head",global.head[1])
ini_write_real("Player1","accs",global.accs[1])
ini_write_real("Player1","skill1",global.skill[1,0]) 
ini_write_real("Player1","skill2",global.skill[1,1]) 
ini_write_real("Player1","skill3",global.skill[1,2]) 
ini_write_real("Player1","skill4",global.skill[1,3]) 
ini_write_real("Player1","skill5",global.skill[1,4]) 
ini_write_real("Player1","skill6",global.skill[1,5]) 
ini_write_real("Player1","skill7",global.skill[1,6]) 
ini_write_real("Player1","skill8",global.skill[1,7]) 
ini_write_real("Player1","skill9",global.skill[1,8]) 

//PLayer 2 stats
ini_write_string("Player2","name",global.name[2])
ini_write_string("Player2","class",global.class[2])
ini_write_string("Player2","status",global.status[2])
ini_write_real("Player2","hp",global.hp[2])
ini_write_real("Player2","mp",global.mp[2])
ini_write_real("Player2","xp",global.xp[2])
ini_write_real("Player2","xp_up",global.xp_up[2])
ini_write_real("Player2","level",global.level[2])
ini_write_real("Player2","maxhp",global.maxhp[2])
ini_write_real("Player2","maxmp",global.maxmp[2])
ini_write_real("Player2","atk",global.atk[2])
ini_write_real("Player2","def",global.def[2])
ini_write_real("Player2","pow",global.pow[2])
ini_write_real("Player2","res",global.res[2])
ini_write_real("Player2","spd",global.spd[2])
ini_write_real("Player2","attack1",global.attack[2,0]) 
ini_write_real("Player2","attack2",global.attack[2,1]) 
ini_write_real("Player2","attack3",global.attack[2,2]) 
ini_write_real("Player2","attack4",global.attack[2,3]) 
ini_write_real("Player2","weapon",global.weapon[2])
ini_write_real("Player2","armor",global.armor[2])
ini_write_real("Player2","head",global.head[2])
ini_write_real("Player2","accs",global.accs[2])
ini_write_real("Player2","skill1",global.skill[2,0]) 
ini_write_real("Player2","skill2",global.skill[2,1]) 
ini_write_real("Player2","skill3",global.skill[2,2]) 
ini_write_real("Player2","skill4",global.skill[2,3]) 
ini_write_real("Player2","skill5",global.skill[2,4]) 
ini_write_real("Player2","skill6",global.skill[2,5]) 
ini_write_real("Player2","skill7",global.skill[2,6]) 
ini_write_real("Player2","skill8",global.skill[2,7]) 
ini_write_real("Player2","skill9",global.skill[2,8]) 

//PLayer 3 stats
ini_write_string("Player3","name",global.name[3])
ini_write_string("Player3","class",global.class[3])
ini_write_string("Player3","status",global.status[3])
ini_write_real("Player3","hp",global.hp[3])
ini_write_real("Player3","mp",global.mp[3])
ini_write_real("Player3","xp",global.xp[3])
ini_write_real("Player3","xp_up",global.xp_up[3])
ini_write_real("Player3","level",global.level[3])
ini_write_real("Player3","maxhp",global.maxhp[3])
ini_write_real("Player3","maxmp",global.maxmp[3])
ini_write_real("Player3","atk",global.atk[3])
ini_write_real("Player3","def",global.def[3])
ini_write_real("Player3","pow",global.pow[3])
ini_write_real("Player3","res",global.res[3])
ini_write_real("Player3","spd",global.spd[3])
ini_write_real("Player3","attack1",global.attack[3,0]) 
ini_write_real("Player3","attack2",global.attack[3,1]) 
ini_write_real("Player3","attack3",global.attack[3,2]) 
ini_write_real("Player3","attack4",global.attack[3,3]) 
ini_write_real("Player3","weapon",global.weapon[3])
ini_write_real("Player3","armor",global.armor[3])
ini_write_real("Player3","head",global.head[3])
ini_write_real("Player3","accs",global.accs[3])
ini_write_real("Player3","skill1",global.skill[3,0]) 
ini_write_real("Player3","skill2",global.skill[3,1]) 
ini_write_real("Player3","skill3",global.skill[3,2]) 
ini_write_real("Player3","skill4",global.skill[3,3]) 
ini_write_real("Player3","skill5",global.skill[3,4]) 
ini_write_real("Player3","skill6",global.skill[3,5]) 
ini_write_real("Player3","skill7",global.skill[3,6]) 
ini_write_real("Player3","skill8",global.skill[3,7]) 
ini_write_real("Player3","skill9",global.skill[3,8]) 


//item data
for(c = 0; c < 75; c += 1){
    ini_write_real("Items","item " + string(c),global.item[c])
}

//remember opened treasure chests
ini_write_string("Misc","openedChests",ds_list_write(global.openChests))

ini_write_real("Misc","player_x",global.player_x)
ini_write_real("Misc","player_y",global.player_y)
ini_write_string("Misc","room",global.field_room)
ini_write_real("Misc","gil",global.money)
ini_write_real("Misc","direction",global.dir)

ini_close();
drawBattleMessage("Save Successful!")


